In [1]:
import numpy as np
import pylab as pl
import scipy as sp
import pandas as pd

In [2]:
anime_recommand_raw = pd.read_csv("./data/anime_recommend.csv")
rating_recommand_raw = pd.read_csv("./data/rating_recommend.csv")
data_anime_raw = pd.read_csv("./data/dataanime.csv")

In [6]:
anime_recommand_raw.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [4]:
rating_recommand_raw.head()

user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [7]:
data_anime_raw.head()

Title   Type Episodes            Status  \
0  Fullmetal Alchemist: Brotherhood     TV       64   Finished Airing   
1                    Kimi no Na wa.  Movie        1   Finished Airing   
2                          Gintama°     TV       51   Finished Airing   
3                     Steins;Gate 0     TV       23  Currently Airing   
4                       Steins;Gate     TV       24   Finished Airing   

  Start airing End airing Starting season             Broadcast time  \
0     2009-4-5   2010-7-4          Spring     Sundays at 17:00 (JST)   
1    2016-8-26          -               -                          -   
2     2015-4-8  2016-3-30          Spring  Wednesdays at 18:00 (JST)   
3    2018-4-12          -          Spring   Thursdays at 01:35 (JST)   
4     2011-4-6  2011-9-14          Spring  Wednesdays at 02:05 (JST)   

                                           Producers  \
0  Aniplex,Square Enix,Mainichi Broadcasting Syst...   
1  Kadokawa Shoten,Toho,Sound Team Don Juan,Lawso...   
2                            TV Tokyo,Aniplex,Dentsu   
3                                          Nitroplus   
4  Frontier Works,Media Factory,Movic,AT-X,Kadoka...   

                       Licensors                Studios       Sources  \
0  Funimation,Aniplex of America                  Bones         Manga   
1           Funimation,NYAV Post       CoMix Wave Films      Original   
2         Funimation,Crunchyroll  Bandai Namco Pictures         Manga   
3                     Funimation              White Fox  Visual novel   
4                     Funimation              White Fox  Visual novel   

                                              Genres         Duration Rating  \
0  Action,Military,Adventure,Comedy,Drama,Magic,F...  24 min. per ep.      R   
1                  Supernatural,Drama,Romance,School    1 hr. 46 min.  PG-13   
2  Action,Comedy,Historical,Parody,Samurai,Sci-Fi...  24 min. per ep.      R   
3                                    Sci-Fi,Thriller  23 min. per ep.  PG-13   
4                                    Sci-Fi,Thriller  24 min. per ep.  PG-13   

   Score  Scored by  Members  Favorites  \
0   9.25     719706  1176368     105387   
1   9.19     454969   705186      33936   
2   9.16      70279   194359       5597   
3   9.16      12609   186331       1117   
4   9.14     552791   990419      90365   

                                         Description  
0  "In order for something to be obtained, someth...  
1  Mitsuha Miyamizu, a high school girl, yearns t...  
2  Gintoki, Shinpachi, and Kagura return as the f...  
3  The dark untold story of Steins;Gate that lead...  
4  The self-proclaimed mad scientist Rintarou Oka...

## Filter the anime

In [3]:

# Select only the anime in the dataset data_anime
anime_id_selected = []

for title in data_anime_raw['Title']:
    current_id = anime_recommand_raw[anime_recommand_raw['name'] == title]['anime_id'].values
    if len( current_id ) > 0:
        anime_id_selected.append( current_id[0] )

In [5]:
anime_id_selected.sort()
anime_id_selected = np.array(anime_id_selected)

In [8]:
anime_id_selected

array([    1,     5,     6, ..., 34349, 34445, 34514], dtype=int64)

## Get the rating of the selected animes from the first 5000 users

In [89]:
rating_table = np.zeros( (5000, len(anime_id_selected)) )

In [9]:
# Not to run if ./data/rating_table.csv exists

# for index, row in rating_recommand_raw.iterrows():
#     if row['user_id'] >= 5000:
#         break
#     if row['anime_id'] in anime_id_selected:
#         rating_table[ row['user_id'] - 1 , np.where( anime_id_selected == row['anime_id'] )[0] ] = row['rating']

In [114]:
pd.DataFrame(rating_table, columns = list(anime_id_selected) ).to_csv("./data/rating_table.csv")

In [18]:
rating_table_df = pd.read_csv("./data/rating_table.csv", index_col = 0)

In [19]:
rating_table_df

1    5    6   15    16   17   18   20   21   24  ...  33988  34076  \
0      0.0  0.0  0.0  0.0   0.0  0.0  0.0 -1.0  0.0 -1.0  ...    0.0    0.0   
1      0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2      0.0  0.0  0.0  0.0   0.0  0.0  0.0  8.0  0.0  0.0  ...    0.0    0.0   
3      0.0  0.0 -1.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4      0.0  0.0  8.0  6.0   0.0  6.0  6.0  6.0  0.0  1.0  ...    0.0    0.0   
...    ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ...    ...    ...   
4995   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4996   0.0  0.0  7.0  0.0  10.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4997  10.0  0.0  8.0  0.0   7.0  0.0  0.0  0.0  0.0  9.0  ...    0.0    0.0   
4998   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  9.0  ...    0.0    0.0   
4999   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

      34103  34136  34240  34284  34299  34349  34445  34514  
0       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
4995    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4996    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4997    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4998    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4999    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5000 rows x 1342 columns]

## Dimension Reduction

In [14]:
from sklearn.decomposition import PCA

In [46]:
pca = PCA(n_components=100)

In [47]:
rating_table = np.array( rating_table_df )

In [48]:
pca.fit(rating_table)

PCA(copy=True, iterated_power='auto', n_components=100, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [49]:
pca.explained_variance_[:] 

array([381.36735975,  80.55146262,  66.78260242,  59.8750564 ,
        56.55784226,  41.16401642,  31.83319218,  29.99930114,
        27.92294821,  24.85925341,  23.90844631,  20.8301011 ,
        19.4069673 ,  18.98337883,  17.83199578,  16.92436563,
        16.14812777,  15.71176865,  15.14526404,  14.46498408,
        14.08361858,  13.90795907,  13.69204975,  13.2001194 ,
        13.09885933,  12.34212762,  12.20052685,  12.05076166,
        11.89733935,  11.69169936,  11.50549486,  11.3586034 ,
        11.24824358,  11.03614257,  10.87200115,  10.7197611 ,
        10.51013817,  10.40546212,  10.34320798,  10.21793566,
         9.87001   ,   9.79023921,   9.60642486,   9.42033361,
         9.28240015,   9.25862735,   9.17089708,   8.91711983,
         8.87728835,   8.78203488,   8.74550735,   8.53645175,
         8.46128373,   8.38764629,   8.30689003,   8.22679092,
         8.16468617,   8.11334671,   8.02226908,   7.91921433,
         7.86393131,   7.80392611,   7.70986768,   7.68

In [53]:
pca.score(rating_table) 

-1883.7861852577262

In [51]:
pca.transform(rating_table).shape

(5000, 100)

In [155]:
def nmf(X, k):
    """
    Args:
        X (np.array, dim: n,m,4): containing the image channel to be processed
        k (int): the number of elements to be used in the low rank approximation 
    
    Returns:
        X_low_rank_approx (np.array, dim: n,m,4): low rank approximation of X
    """
    
#     X_low_rank_approx = np.zeros(X.shape)
#     for i in range(4):
    A_0, D, B_0 = np.linalg.svd(X, full_matrices=False)
    A = np.abs(A_0[:,:k])
    B = np.abs(B_0[:k,:])

    for _ in range(65):
        B = np.nan_to_num(B * (A.T.dot(X))/(A.T.dot(A.dot(B))))
        A = np.nan_to_num(A * (X.dot(B.T)) / (A.dot(B.dot(B.T))))
    return A, B

In [156]:
A, B = nmf(rating_table, 10)

C:\Users\Automne\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Automne\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


In [151]:
A.shape

(5000, 10)

In [152]:
C = A.dot(B)

In [153]:
def evals(X, X_low_rank_approx):
    """
    Args:
        X (np.array, dim: n,m,4): containing the image channel to be processed
        X_low_rank_approx (np.array, dim: n,m,4): low rank approximation of X
    Returns:
        eval_fraction (float): the ratio of the explained variance as described in the problem description
    """
    
    sigma_k, U_k = np.linalg.eig( X_low_rank_approx.T.dot( X_low_rank_approx) )
    sigma, U = np.linalg.eig(X.T.dot(X))
    return np.sum(sigma_k).real / np.sum(sigma).real
    

In [157]:
evals(rating_table, C)

0.34877788796078774

In [159]:
C

array([[-1.72084169e-01, -6.44372668e-02, -1.44491670e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.77515828e-07,  2.44176622e-15,  1.59586601e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.78096670e+00,  7.26606907e-01,  8.82604814e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.25353742e+00,  6.15424287e-01,  1.63498660e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.82358209e+00,  7.87312118e-01,  1.19948562e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])